"""Shared implementation for WS53 CLI Get Started docs and non-HIL CI."""

from tools.docs.get_started.contract import (
    ARTIFACTS,
    CHIP,
    CLI_COMMIT,
    CLI_REPOSITORY,
    CLI_VERSION,
    COMMAND_GROUPS,
    CONFIG_PATH,
    EXPECTED_IMAGE_OS_PREFIXES,
    EXPECTED_MACHINES,
    EXPECTED_RUNNER_LABELS,
    GENERATED_SECTIONS,
    PLATFORM_COMPILERS,
    SDK_BRANCH,
    SDK_REMOTE_COMMAND,
    SDK_REPOSITORY,
    SDK_VERSION,
    SDK_VERSION_SOURCE,
    TARGET,
    TOOLCHAIN_VERSION,
    Command,
)
from tools.docs.get_started.evidence import _expected_step_argv, validate_evidence
from tools.docs.get_started.render import (
    boundary_marker,
    placeholder,
    render_document,
    render_section,
    validate_document_source,
)
from tools.docs.get_started.runner import (
    StepEvidence,
    StepExecutionFailure,
    ValidationFailure,
    run_validation,
)

__all__ = [
    "ARTIFACTS",
    "CHIP",
    "CLI_COMMIT",
    "CLI_REPOSITORY",
    "CLI_VERSION",
    "COMMAND_GROUPS",
    "CONFIG_PATH",
    "EXPECTED_IMAGE_OS_PREFIXES",
    "EXPECTED_MACHINES",
    "EXPECTED_RUNNER_LABELS",
    "GENERATED_SECTIONS",
    "PLATFORM_COMPILERS",
    "SDK_BRANCH",
    "SDK_REMOTE_COMMAND",
    "SDK_REPOSITORY",
    "SDK_VERSION",
    "SDK_VERSION_SOURCE",
    "TARGET",
    "TOOLCHAIN_VERSION",
    "Command",
    "StepEvidence",
    "StepExecutionFailure",
    "ValidationFailure",
    "_expected_step_argv",
    "boundary_marker",
    "placeholder",
    "render_document",
    "render_section",
    "run_validation",
    "validate_document_source",
    "validate_evidence",
]
